cask_args appdir: "/Applications"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "bash-completion"
brew "git"
brew "hub"
brew "neovim"
brew "python"
brew "telnet"
brew "the_silver_searcher"
brew "tmux"
brew "vim"
brew "wget"
brew "go"
cask "emacs"
cask "graphiql"
cask "minikube"
cask "spectacle"
cask "itsycal"
cask "flux"
cask "sublime-text"
cask "visual-studio-code"
cask "google-chrome"
cask "iterm2"
cask "font-input"
# brew "clojure"
# brew "imagemagick"
# brew "leiningen"
# brew "node-build"
# brew "nodenv"
# brew "ruby-build"
# brew "rbenv"
# brew "redis"
# brew "shpotify"
# brew "zsh"
# tap "mongodb/brew"
